spring.datasource.url=jdbc:mysql://database-2.ce0m1hw3nsaw.us-east-1.rds.amazonaws.com:3306/Sucursal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=admin
spring.datasource.password=mikod123
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
